112  add trip stop sequence
TIDES-transit/TIDES pull request #132
Opened 2023-04-28 19:15 UTC by jaygordon

# Pull Request

Before submitting a pull request, please read [CONTRIBUTING.md](CONTRIBUTING.md).

For spec changes:

- [x] Pull-requests must address an existing issue
- [x] Update relevant documentation.

By contributing to this project, all contributors certify to the Developer Certificate of Origin in [CONTRIBUTING.md](CONTRIBUTING.md#contributor-agreement).

2023-05-08 16:45 UTC, botanize requested changes
- [ ] add `title` parameter to `trip_stop_sequence` field, in all tables, see comments for format.
- [ ] clarify `trip_stop_sequence` description property in all tables
- [ ] remove required constraint from `trip_stop_sequence` in `vehicle_locations` table

2023-05-08 16:45 UTC, botanize commented on spec/fare_transactions.schema.json
> +      "description": "The temporal sequence of this transaction's enclosing stop visit, if any, within its performed trip, starting at 1 and containing no gaps. This may differ from scheduled_stop_se
I find the description a bit unclear. Maybe something more akin to the GTFS stop_sequence language: 
```
"The actual order of stops visited within a performed trip. The values must start at 1 and must be consecutive along the trip.<br/> Example: A bus departs the first stop and detours around the second and third scheduled stops, visiting one unscheduled stop and resuming regular service at the 4th scheduled stop. The `scheduled_stop_sequence` is [1, null, 4], and the `trip_stop_sequence` is [1, 2, 3]."

2023-05-08 16:45 UTC, botanize commented on spec/vehicle_locations.schema.json
> +        "required": true,
I see we're transferring the required constraint to `trip_stop_sequence`. However, if `trip_id_performed` isn't required I'm not sure how to make sense of `trip_stop_sequence` being required. Let's drop the required constraint on this field.

2023-05-09 12:43 UTC, jaygordon commented on spec/fare_transactions.schema.json
> +      "description": "The temporal sequence of this transaction's enclosing stop visit, if any, within its performed trip, starting at 1 and containing no gaps. This may differ from scheduled_stop_se
Added

2023-05-10 16:39 UTC, botanize requested changes
Thank you Jay! This looks good, but the JSON doesn't validate because there are some commas missing. I've noted the locations in the comments.

- [ ] add missing a comma at the end of the description property lines for the `trip_stop_sequence` field.

2023-05-10 16:39 UTC, botanize commented on spec/fare_transactions.schema.json
> +      "description": "The actual order of stops visited within a performed trip. The values must start at 1 and must be consecutive along the trip.<br/> Example: A bus departs the first stop and deto
Missing a comma at the end of this line to separate `description` from `constraints`

2023-05-10 16:39 UTC, botanize commented on spec/passenger_events.schema.json
> +      "description": "The actual order of stops visited within a performed trip. The values must start at 1 and must be consecutive along the trip.<br/> Example: A bus departs the first stop and deto
Missing a comma at the end of this line to separate `description` from `constraints`

2023-05-10 16:39 UTC, botanize commented on spec/stop_visits.schema.json
> +      "description": "The actual order of stops visited within a performed trip. The values must start at 1 and must be consecutive along the trip.<br/> Example: A bus departs the first stop and deto
Missing a comma at the end of this line to separate `description` from `constraints`

2023-05-10 16:39 UTC, botanize commented on spec/vehicle_locations.schema.json
> +      "description": "The actual order of stops visited within a performed trip. The values must start at 1 and must be consecutive along the trip.<br/> Example: A bus departs the first stop and deto
Missing a comma at the end of this line to separate `description` from `constraints`

2023-06-14 19:26 UTC, e-lo commented
@jaygordon can you also update the `architecture.md` mermaid diagram where applicable to reflect these term changes?

2023-06-28 21:56 UTC, jlstpaul commented
@jaygordon If you have addressed @botanize comments, I think this can move forward.

2023-07-11 17:49 UTC, e-lo commented
I think something like this would be fine:

```
stop_times.txt --> |"
        stop_times.txt: stop_id,stop_sequence
        stop_visits: stop_id,scheduled_stop_sequence
    "| stop_visits

```

```mermaid

graph LR;
stop_times.txt --> |"
        stop_times.txt: stop_id,stop_sequence
        stop_visits: stop_id,scheduled_stop_sequence
    "| stop_visits

```

Note: in [mermaid.live](https://mermaid.live/) you can use markdown which is prettier...but that doesn't seem to consistently render in github :-/

2023-08-09 20:41 UTC, SorenSpicknall approved these changes

2023-08-09 20:41 UTC, merged