WIP: Experiments with forked or new JSON validator
TIDES-transit/TIDES pull request #149
Opened 2023-07-06 21:06 UTC by SorenSpicknall

# Pull Request
This PR will hopefully address #136 when complete. Starting out by attempting to fork the existing validator and substitute a different Python Docker image underneath it, since the existing validator is unmaintained and causing errors.

2023-07-06 22:06 UTC, e-lo requested changes
Let's at a min put the image under a non-personal GH account :-)

2023-07-07 15:43 UTC, SorenSpicknall commented on .github/workflows/validate_package_schema.yml
> +        uses: SorenSpicknall/json-schema-validator@master
The trouble we have right now is that Frictionless primarily references and uses the JSON schema standard `draft-04`, which is not supported by recent versions of the popular ajv JSON validation tool that underlies most of the available GitHub actions that perform this task. This limits our options for externally supported automations; if we used `draft-07` instead, we could rely on [the well-maintained `json-yaml-validate` Action](https://github.com/marketplace/actions/json-yaml-validate), but that would mean a lot of departure from standard Frictionless stuff.

I will modify this PR to use [the `validate-json` Action](https://github.com/marketplace/actions/validate-json), which relies on an older version of ajv and supports `draft-04`. The downside to that one is we need to manually list each of the JSON files we're validating within the workflow YAML, so if/when somebody adds a new table schema down the road it won't get picked up for validation until the table is referenced in the workflow definition.

2023-07-07 20:54 UTC, SorenSpicknall commented
Okay, so here's where we're at:

The most popular actively maintained JSON validator Action doesn't work for our purposes because A.) it uses a version of ajv that doesn't support `draft-04`, and B.) if we upgrade to `draft-07` the validator doesn't give us the option to directly set the ajv setting that controls strict interpretation of unknown keywords - so the validator fails on keywords like `propertyOrder` and `context` due to ajv opinionated contravention of [general JSON Schema implementation guidelines](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-6.5).

Most of the other validator Actions out there have some version of the same problem. So I forked the original validator into the TIDES GitHub organization, which is flexible enough to work for our purposes but introduces a possible future maintenance burden.

In addition, I went ahead and updated JSON Schema standard referenced by `tides-data-package.json` and `data-schema.json` to use `draft-07` (which doesn't require changes in our schemas, since the only breaking changes from `draft-04` to `draft-07` aren't applicable to our implementation). The intent here is to give us a head start on future alignment with a newer, more widely used version of the standard and enable us to hook into externally maintained validation tools later if one meets our needs. However, since the examples from Frictionless still use `draft-04` and these files pass CI now either way, I can be persuaded to use `draft-04` instead to remain in alignment with those examples for now. Happy to go in either direction based on your input, @e-lo.

2023-07-11 20:38 UTC, e-lo commented
@SorenSpicknall wondering if this is actually now moot with new version released just now: https://github.com/frictionlessdata/frictionless-ci/pull/48

2023-07-12 15:40 UTC, SorenSpicknall commented
> @SorenSpicknall wondering if this is actually now moot with new version released just now: [frictionlessdata/frictionless-ci#48](https://github.com/frictionlessdata/frictionless-ci/pull/48)

My understanding from the description of #136 and a quick glance at the docs is that the Frictionless-maintained Action is solely geared toward data validation right now, and doesn't support schema validation. That's why we've been using the other Action, `json-schema-validator`. The Dockerfile update that was made to the Frictionless-maintained Action doesn't appear to be directly related to the problems we had with the Action we're using, unless there's something I'm missing.

It's definitely worth continuing to keep the Frictionless tool on the edge of our vision in case they add schema validation in the future, since a community-maintained option that suits our needs would certainly be nicer to work with than the fork used in this PR, but I don't believe the Frictionless-maintained Action supports the functionality we're looking for right now.

2023-07-12 20:48 UTC, e-lo approved these changes
Let's try it out...drumroll...

2023-07-12 20:51 UTC, merged