Add instructions and flags for developing on local fork
TIDES-transit/TIDES pull request #194
Opened 2023-12-01 00:24 UTC by e-lo

Fixes #193

2023-12-01 18:13 UTC, e-lo commented
This is where the change was - as rendered at the link above (to facilitate a quicker review): 
<img width="967" alt="image" src="https://github.com/TIDES-transit/TIDES/assets/794787/b1fa836e-03bc-42b1-9d07-06f56c152215">

2023-12-01 19:10 UTC, botanize requested changes
I don't think the instructions for pushing your forked repo branch to the TIDES repo will work without first setting up the TIDES repo as a remote.

2023-12-01 20:42 UTC, botanize commented on CONTRIBUTING.md
> +    git push origin <my-feature-branch-name>
My understanding is that github tracks the relationship on github, but when you `git clone` your fork, you're setting up just the remote of your fork (as origin). If you want to push from your local clone of your fork to TIDES-transit/TIDES, you'd have to add the upstream yourself. You've forked the repo, you could test it out!

2023-12-04 20:03 UTC, botanize approved these changes

2023-12-04 20:42 UTC, merged